config/routes.rb
Wikiful::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users

  get "welcome/index"

    root 'welcome#index'

    resources :articles
    resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base

belongs_to :user

has_many :article_categories
has_many :categories, through: :article_categories

validates :title, presence: true
validates :content, presence: true
validates :categories, presence: true

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
 
  belongs_to :article 
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :article_categories
	has_many :articles, through: :article_categories

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :articles
  validates_uniqueness_of :email
  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def get_categories
    @categories = Category.all.order(:name)
  end

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authorize, only: [:new]

  def index
    @articles = Article.order(updated_at: :desc).limit(25)
  end

 
  def show
     @article = Article.find(params[:id])
  end

  def new
  @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render "new"
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :content, :category_ids => [])
    end

  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(:name)
  end

  def show
     @category = Category.find(params[:id])
  end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) # get this for free from has_secure_password
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"
   else
     flash.now.alert = "Email or password is invalid"
     render "new"
   end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    	session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up"
    else
      render "new"
    end
  end

  private 
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recent_articles = Article.all.last(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @article.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/categories/index.html.erb
<h1>Wikiful Categories</h1>
   <h3>Click on any link below to see articles tagged with the category</h3>
   <ul>
      <% @categories.each do |category| %>
      <h4>
        <%= link_to category.name, category %>
      </h4>
    <% end %>
    </ul>

app/views/categories/show.html.erb
 <h1><%= @category.name %> Articles</h1>
  <h3>There are <%= @category.articles.count %> articles filed under <%= @category.name %></h3>
  <ul>
     <% @category.articles.order(:title).each do |article| %>
      <h4>
       <%= link_to article.title, article %>
     </h4>
     <% end %>
 </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikifulDemo</title>
    <!--[if lt IE 9]> <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script> <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Wikiful", root_path, :class => "brand" %>
       
       <div class="session-controls"> 
         <% if current_user %>
           <%= link_to "Log Out", logout_path, :class => 'btn btn-primary btn-mini' %>
             Logged in as <%= current_user.email %>.
         <% else %>
           <div class="btn-group">
              <%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
             <%= link_to "Log In", new_session_path, :class => "btn btn-mini" %>
    </div>
  <% end %>
</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="span4">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
 
  <div class="span3 sidebar">
  <div class="my-wiki-site">
    <h4>My Wikiful</h4>
    <ul>
      <li><%= link_to "Write a Wiki", new_article_path %></li>
    </ul>
  </div>


  <div class="categories-sidebar">
    <h4>Categories</h4>
    <ul>
      <% @categories.each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
    </ul>
  </div>
  <div class="about">
    <h4>About Wikiful</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto earum neque perspiciatis quia animi debitis quod repellat vitae explicabo. Sapiente aliquam reprehenderit id vitae atque ducimus facere molestias soluta?</p>
  </div>
</div>

</div>
</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %> 
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %> 
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %> 
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> 
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<p class="lead">Welcome to Wikiful. Most recent articles below:</p>
 <div class="articles">
   <% @recent_articles.each do |article| %>
     <h2>
       <%= link_to article.title, article %>
    </h2>
    <div class="article-info">
    Published <%= article.created_at.strftime('%b %d, %Y') %> |
     Filed under <%= article.categories.map { |category| link_to category.name, category_path(category.id)}.join(', ').html_safe %> 
     </div>
     <div class="content">
       <%= truncate(article.content, :length => 400) %><br />
       <%= link_to "Read more", article %>
     </div>
   <% end %>
 </div>